# Generated by Django 5.0.3 on 2024-04-15 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Marca', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('nombre_usuario', models.CharField(blank=True, max_length=200)),
                ('correo_electronico', models.CharField(max_length=200, unique=True)),
                ('contraseña', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('visitante', 'Usuario Visitante')], default='visitante', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_consola', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('especificaciones', models.TextField()),
                ('caracteristicas', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='consolas/')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.marca_consola')),
            ],
        ),
    ]
